version: '3.8'

services:
  n8n_editor:
    image: n8nio/n8n:1.101.1
    environment:
      NODE_OPTIONS: --max-old-space-size=2048
      N8N_RUNNERS_ENABLED: 'true'
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: 'true'

      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n_fila
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: ${PASSWORD_32_LENGTH}

      N8N_ENCRYPTION_KEY: ${PASSWORD_32_LENGTH}
      N8N_HOST: n8napp.${DOMAIN}
      N8N_EDITOR_BASE_URL: https://n8napp.${DOMAIN}/
      N8N_PROTOCOL: https
      NODE_ENV: production
      WEBHOOK_URL: https://n8nwebhookapp.${DOMAIN}/

      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379
      QUEUE_BULL_REDIS_DB: 2

      NODE_FUNCTION_ALLOW_EXTERNAL: moment,lodash
      EXECUTIONS_DATA_PRUNE: 'true'
      EXECUTIONS_DATA_MAX_AGE: 336
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.n8n_editor.rule=Host(`n8napp.${DOMAIN}`)
        - traefik.http.routers.n8n_editor.entrypoints=websecure
        - traefik.http.routers.n8n_editor.tls.certresolver=le
        - traefik.http.routers.n8n_editor.service=n8n_editor
        - traefik.http.services.n8n_editor.loadbalancer.server.port=5678
    networks:
      - traefik_public
      - general_network

  n8n_webhook:
    image: n8nio/n8n:1.101.1
    command: webhook
    environment:
      NODE_OPTIONS: --max-old-space-size=2048
      N8N_RUNNERS_ENABLED: 'true'
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: 'true'

      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n_fila
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: ${PASSWORD_32_LENGTH}

      N8N_ENCRYPTION_KEY: ${PASSWORD_32_LENGTH}
      N8N_HOST: n8napp.${DOMAIN}
      N8N_EDITOR_BASE_URL: https://n8napp.${DOMAIN}/
      N8N_PROTOCOL: https
      NODE_ENV: production
      WEBHOOK_URL: https://n8nwebhookapp.${DOMAIN}/

      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379
      QUEUE_BULL_REDIS_DB: 2

      NODE_FUNCTION_ALLOW_EXTERNAL: moment,lodash
      EXECUTIONS_DATA_PRUNE: 'true'
      EXECUTIONS_DATA_MAX_AGE: 336
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '0.5'
          memory: 1024M
      labels:
        - traefik.enable=true
        - traefik.http.routers.n8n_webhook.rule=Host(`n8nwebhookapp.${DOMAIN}`)
        - traefik.http.routers.n8n_webhook.entrypoints=websecure
        - traefik.http.routers.n8n_webhook.tls.certresolver=le
        - traefik.http.routers.n8n_webhook.service=n8n_webhook
        - traefik.http.services.n8n_webhook.loadbalancer.server.port=5678
    networks:
      - traefik_public
      - general_network

  n8n_worker:
    image: n8nio/n8n:1.101.1
    command: worker --concurrency=5
    environment:
      NODE_OPTIONS: --max-old-space-size=2048
      N8N_RUNNERS_ENABLED: 'true'
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: 'true'
      OFFLOAD_MANUAL_EXECUTIONS_TO_WORKERS: 'true'

      DB_TYPE: postgresdb
      DB_POSTGRESDB_HOST: postgres
      DB_POSTGRESDB_PORT: 5432
      DB_POSTGRESDB_DATABASE: n8n_fila
      DB_POSTGRESDB_USER: postgres
      DB_POSTGRESDB_PASSWORD: ${PASSWORD_32_LENGTH}

      N8N_ENCRYPTION_KEY: ${PASSWORD_32_LENGTH}
      N8N_HOST: n8napp.${DOMAIN}
      N8N_EDITOR_BASE_URL: https://n8napp.${DOMAIN}/
      N8N_PROTOCOL: https
      NODE_ENV: production
      WEBHOOK_URL: https://n8nwebhookapp.${DOMAIN}/

      EXECUTIONS_MODE: queue
      QUEUE_BULL_REDIS_HOST: redis
      QUEUE_BULL_REDIS_PORT: 6379
      QUEUE_BULL_REDIS_DB: 2

      NODE_FUNCTION_ALLOW_EXTERNAL: moment,lodash
      EXECUTIONS_DATA_PRUNE: 'true'
      EXECUTIONS_DATA_MAX_AGE: 336
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: '1.0'
          memory: 2048M
    networks:
      - traefik_public
      - general_network

networks:
  traefik_public:
    external: true
  general_network:
    external: true
